'use strict';

// tests for dumpEnv
// Generated by serverless-mocha-plugin

const mod = require('../dumpenv.js');
const mochaPlugin = require('../.serverless_plugins/serverless-mocha-plugin/index.js');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

describe('dumpEnv', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('Check env', () => {
    return wrapped.run({}).then((response) => {
      expect(process.env.TEST_REGION).to.be.equal('us-east-1');
    });
  });
});
